/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * layer2 hub
 * This spec defines the API for layer2 hub 
 *
 * OpenAPI spec version: 0.0.0
 * Contact: alexvlewis@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface JSONGeneric
 */
export interface JSONGeneric {
}


/**
 * LcApi - fetch parameter creator
 * @export
 */
export const LcApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Close ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeLC(body: JSONGeneric, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling closeLC.');
            }
            const localVarPath = `/v1/lc/close`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JSONGeneric" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Offer to open a ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openLC(body: JSONGeneric, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling openLC.');
            }
            const localVarPath = `/v1/lc/open`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JSONGeneric" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Offer to update a ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLC(body: JSONGeneric, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateLC.');
            }
            const localVarPath = `/v1/lc/update`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JSONGeneric" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LcApi - functional programming interface
 * @export
 */
export const LcApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Close ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeLC(body: JSONGeneric, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JSONGeneric> {
            const localVarFetchArgs = LcApiFetchParamCreator(configuration).closeLC(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Offer to open a ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openLC(body: JSONGeneric, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JSONGeneric> {
            const localVarFetchArgs = LcApiFetchParamCreator(configuration).openLC(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Offer to update a ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLC(body: JSONGeneric, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JSONGeneric> {
            const localVarFetchArgs = LcApiFetchParamCreator(configuration).updateLC(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * LcApi - factory interface
 * @export
 */
export const LcApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Close ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeLC(body: JSONGeneric, options?: any) {
            return LcApiFp(configuration).closeLC(body, options)(fetch, basePath);
        },
        /**
         * Offer to open a ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openLC(body: JSONGeneric, options?: any) {
            return LcApiFp(configuration).openLC(body, options)(fetch, basePath);
        },
        /**
         * Offer to update a ledger channel with Ingrid
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLC(body: JSONGeneric, options?: any) {
            return LcApiFp(configuration).updateLC(body, options)(fetch, basePath);
        },
    };
};

/**
 * LcApi - object-oriented interface
 * @export
 * @class LcApi
 * @extends {BaseAPI}
 */
export class LcApi extends BaseAPI {
    /**
     * Close ledger channel with Ingrid
     * @param {} body Channel data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LcApi
     */
    public closeLC(body: JSONGeneric, options?: any) {
        return LcApiFp(this.configuration).closeLC(body, options)(this.fetch, this.basePath);
    }

    /**
     * Offer to open a ledger channel with Ingrid
     * @param {} body Channel data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LcApi
     */
    public openLC(body: JSONGeneric, options?: any) {
        return LcApiFp(this.configuration).openLC(body, options)(this.fetch, this.basePath);
    }

    /**
     * Offer to update a ledger channel with Ingrid
     * @param {} body Channel data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LcApi
     */
    public updateLC(body: JSONGeneric, options?: any) {
        return LcApiFp(this.configuration).updateLC(body, options)(this.fetch, this.basePath);
    }

}

/**
 * VcApi - fetch parameter creator
 * @export
 */
export const VcApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Close virtual channel with Alice/Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeVC(body: JSONGeneric, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling closeVC.');
            }
            const localVarPath = `/v1/vc/close`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JSONGeneric" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Offer to open a virtual channel with Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openVC(body: JSONGeneric, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling openVC.');
            }
            const localVarPath = `/v1/vc/open`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JSONGeneric" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Offer to update a virtual channel with Alice/Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVC(body: JSONGeneric, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateVC.');
            }
            const localVarPath = `/v1/vc/update`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"JSONGeneric" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VcApi - functional programming interface
 * @export
 */
export const VcApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Close virtual channel with Alice/Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeVC(body: JSONGeneric, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JSONGeneric> {
            const localVarFetchArgs = VcApiFetchParamCreator(configuration).closeVC(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Offer to open a virtual channel with Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openVC(body: JSONGeneric, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JSONGeneric> {
            const localVarFetchArgs = VcApiFetchParamCreator(configuration).openVC(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Offer to update a virtual channel with Alice/Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVC(body: JSONGeneric, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<JSONGeneric> {
            const localVarFetchArgs = VcApiFetchParamCreator(configuration).updateVC(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * VcApi - factory interface
 * @export
 */
export const VcApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Close virtual channel with Alice/Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeVC(body: JSONGeneric, options?: any) {
            return VcApiFp(configuration).closeVC(body, options)(fetch, basePath);
        },
        /**
         * Offer to open a virtual channel with Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openVC(body: JSONGeneric, options?: any) {
            return VcApiFp(configuration).openVC(body, options)(fetch, basePath);
        },
        /**
         * Offer to update a virtual channel with Alice/Bob
         * @param {JSONGeneric} body Channel data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVC(body: JSONGeneric, options?: any) {
            return VcApiFp(configuration).updateVC(body, options)(fetch, basePath);
        },
    };
};

/**
 * VcApi - object-oriented interface
 * @export
 * @class VcApi
 * @extends {BaseAPI}
 */
export class VcApi extends BaseAPI {
    /**
     * Close virtual channel with Alice/Bob
     * @param {} body Channel data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcApi
     */
    public closeVC(body: JSONGeneric, options?: any) {
        return VcApiFp(this.configuration).closeVC(body, options)(this.fetch, this.basePath);
    }

    /**
     * Offer to open a virtual channel with Bob
     * @param {} body Channel data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcApi
     */
    public openVC(body: JSONGeneric, options?: any) {
        return VcApiFp(this.configuration).openVC(body, options)(this.fetch, this.basePath);
    }

    /**
     * Offer to update a virtual channel with Alice/Bob
     * @param {} body Channel data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcApi
     */
    public updateVC(body: JSONGeneric, options?: any) {
        return VcApiFp(this.configuration).updateVC(body, options)(this.fetch, this.basePath);
    }

}

